const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
function boot(saved){const storage=new Map(saved?[['oplen-mirror-scale-v2',JSON.stringify(saved)]]:[]),context={crypto:require('node:crypto').webcrypto,TextEncoder,structuredClone,URL,URLSearchParams,Response,FormData,File:class{},Event:class{},console,confirm:()=>true,location:{href:'https://demo.oplen.io/',origin:'https://demo.oplen.io',search:'',reload(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},sessionStorage:{clear(){}},MutationObserver:class {observe(){}},document:{querySelector:()=>null},XMLHttpRequest:class {open(){}send(){}},window:{fetch:()=>{throw Error('Unexpected network')}}};vm.runInNewContext(fs.readFileSync('demo/backend.js','utf8'),context);return {context,storage,request:async(body,query='')=>(await context.window.fetch('https://demo.oplen.io/api/management.php?view=person&userId='+query,{method:body?'POST':'GET',body:body?JSON.stringify({csrf:'demo-local',...body}):undefined})).json()}}
(async()=>{const env=boot(),first=await env.request(null,'2');assert(first.ok);assert.equal(first.data.person.id,2);assert.equal(first.data.evaluations.length,1);assert.equal(first.data.evaluations[0].gaps.length,2);assert.equal(first.data.training.needs.length,1);assert.equal(first.data.training.courses.length,1);assert.equal(first.data.training.courses[0].result.validatedRoi,50);assert(!('email' in first.data.person));assert(!('permissions' in first.data.person));
 const other=await env.request(null,'12');assert(other.ok);assert.equal(other.data.person.id,12);assert.equal(other.data.training.needs.length,0);assert.equal(other.data.training.courses.length,0);
 env.context.location.search='?previewUser=2';assert(!(await env.request(null,'3')).ok);const self=await env.request(null,'2');assert(self.ok&&self.data.canSeePaths&&!self.data.canSeeTraining);assert.equal(self.data.training,null);
 const saved=env.context.window.OplenDemo.snapshot(),manager=saved.people.find(p=>p.id===11);saved.people=[manager,...saved.people.filter(p=>p.id!==11)];const scope=boot(saved);assert(!(await scope.request(null,'2')).ok);const team=await scope.request(null,'12');assert(team.ok&&team.data.canSeeTraining&&!team.data.canSeePaths);assert.equal(team.data.paths,null);
 saved.people.find(p=>p.id===12).department='Marketing';assert(!(await boot(saved).request(null,'12')).ok);
 env.context.location.search='';const all=env.context.window.OplenDemo.snapshot();all.paths=[{id:1,user_id:12,title:'Ruta de otra persona',status:'active',duration_weeks:4},{id:2,title:'Ruta antigua sin asignación',status:'active',duration_weeks:4}];const paths=boot(all);assert.equal((await paths.request(null,'2')).data.paths.length,0);assert.equal((await paths.request(null,'12')).data.paths.length,1);assert.equal(paths.context.window.OplenDemo.snapshot().paths.length,2);
 console.log('PASS demo dossiers: target isolation, published gaps, group ROI, paths ownership, manager scope, preview and transfers');
})().catch(e=>{console.error(e);process.exit(1)});
