const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
function boot(saved){const storage=new Map(saved?[['oplen-mirror-scale-v2',JSON.stringify(saved)]]:[]),context={crypto:require('node:crypto').webcrypto,TextEncoder,structuredClone,URL,URLSearchParams,Response,FormData,File:class{},Event:class{},console,confirm:()=>true,location:{href:'https://demo.oplen.io/',origin:'https://demo.oplen.io',search:'',reload(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},sessionStorage:{clear(){}},MutationObserver:class {observe(){}},document:{querySelector:()=>null},XMLHttpRequest:class {open(){}send(){}},window:{fetch:()=>{throw Error('Unexpected network')}}};vm.runInNewContext(fs.readFileSync('demo/backend.js','utf8'),context);return {context,storage,request:async(body,query='')=>(await context.window.fetch('https://demo.oplen.io/api/training.php'+query,{method:body?'POST':'GET',body:body?JSON.stringify({csrf:'demo-local',...body}):undefined})).json()}}
(async()=>{const env=boot(),first=await env.request();assert(first.ok);assert.equal(first.data.people.length,99);assert.equal(first.data.dashboard.rows.length,99);assert.equal(first.data.needs.length,8);assert.equal(first.data.courses.length,3);assert(first.data.dashboard.rows.some(r=>r.cells.some(c=>c.gap>0)));const r=first.data.courses.find(r=>r.result.latestDay===90);assert.equal(r.result.cost,15000);assert.equal(r.result.validatedBenefit,22500);assert.equal(r.result.validatedRoi,50);assert.equal(first.data.courses.find(r=>r.data.status==='planned').result.validatedRoi,null);
 const person=first.data.people[0],need={action:'save-need',userId:person.id,title:'Necesidad de documentación',cause:'skills',intervention:'training',status:'validated',goal:'Documentar casos con evidencia y criterio',evidence:'Revisión de casos operativos de ejemplo',dueDate:'2027-01-01',ownerId:1};const created=await env.request(need);assert(created.ok);assert(!(await env.request({...need,csrf:'bad'})).ok);assert(!(await env.request({...need,cause:'tools'})).ok);assert(!(await env.request({...need,id:created.id,revision:0})).ok);
 const source=first.data.dashboard.rows.find(r=>r.cells.some(c=>c.gap>0));const imported=await env.request({...need,userId:source.userId,evaluationId:source.evaluationId,criterionKey:source.cells[0].key});assert(imported.ok);assert((await env.request()).data.needs.find(n=>n.id===imported.id).data.source);
 const course={action:'save-course',participantIds:[person.id],needId:created.id,title:'Mejora operativa',provider:'Academia ficticia',status:'completed',endDate:'2025-01-01',goal:need.goal,metric:'Errores mensuales',unit:'errores',baseline:20,target:5,tuition:1000,travel:200,extras:100,hours:10,hourlyRate:20,costsConfirmed:true,costEvidence:'Facturas y horas ficticias verificadas',estimatedBenefit:3000,estimatedDays:90,assumptions:'Retrabajo evitado según casos de ejemplo'};const made=await env.request(course);assert(made.ok);const cut={action:'checkpoint',id:made.id,revision:1,day:30,observedOn:'2025-12-01',metricValue:10,grossBenefit:2000,attribution:50,evidence:'Evidencia ficticia de retrabajo revisada',validated:true};assert((await env.request(cut)).ok);assert(!(await env.request({...cut,revision:2})).ok);assert((await env.request({...cut,day:90,revision:2,grossBenefit:4000,attribution:75})).ok);const final=(await env.request()).data.courses.find(r=>r.id===made.id);assert.equal(final.result.validatedBenefit,3000);assert.equal(final.result.validatedRoi,100);assert(!(await env.request({...course,id:made.id,revision:3,currency:'USD'})).ok);
 const saved=env.context.window.OplenDemo.snapshot();saved.company.name='Nombre personalizado';const persisted=boot(saved);assert.equal((await persisted.request()).data.courses.length,4);assert.equal(persisted.context.window.OplenDemo.snapshot().company.name,'Nombre personalizado');assert.equal(saved.people.length,100);env.context.location.search='?previewUser=2';assert(!(await env.request()).ok);env.context.location.search='';assert(!(await env.request(null,'?asUser=2')).ok);assert(!(await env.request(null,'?period=2026-B7')).ok);
 console.log('PASS demo training: scale preserved, seed gaps, DNC, source evidence, ROI, revisions, immutable checkpoints, preview protection and local persistence');
})().catch(e=>{console.error(e);process.exit(1)});
